# Generated by Django 5.1.6 on 2025-02-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_order', to='app.sale')),
                ('warranty_claim', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_order', to='app.warrantyclaim')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('sale__isnull', False), ('warranty_claim__isnull', False)), models.Q(('sale__isnull', True), ('warranty_claim__isnull', True)), _connector='OR'), name='sale_or_warranty_claim', violation_error_message='Either sale or warranty_claim must be set')],
            },
        ),
    ]
