# Generated by Django 5.1.6 on 2025-02-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplyorder',
            name='sale_or_warranty_claim',
        ),
    ]
